/**
 * Compatibility shim: the Cloudinary upload helpers, backed by local disk.
 *
 * These two functions took a buffer or a data URL, signed it and POSTed it to
 * `api.cloudinary.com`. That account (`dx26sj1as`) is disabled -- the API
 * answers `{"error":{"message":"cloud_name is disabled"}}` to every request --
 * so every taxi image upload was failing in production: driver documents and
 * selfies, pooling route images, and the landing-page content uploader.
 *
 * The food and quick-commerce modules hit the same wall earlier and were
 * repointed at services/storage.service.js (see cloudinary.service.js, which
 * does this for their sixty-odd call sites). Taxi was left on the live API and
 * kept failing.
 *
 * Same names, same arguments, same return shape, so no caller changes. What is
 * different is where the bytes go and what they become: storage.service.js
 * converts every image to WebP -- resized to UPLOAD_WEBP_MAX_WIDTH, lossless
 * when there is an alpha channel so transparency does not fringe -- which is
 * what the rest of the platform already serves.
 *
 * `format` is accepted and ignored. It was how a caller asked Cloudinary for a
 * particular output, and one caller passed `undefined` meaning "keep the
 * original" -- a JPEG selfie stored as a JPEG. Everything is WebP now, which is
 * the point of routing through here, so honouring that would mean keeping the
 * one path that does not.
 *
 * `publicId` comes back as the file's path under the upload root, which is what
 * deleteStoredFile takes -- the same trade cloudinary.service.js made.
 *
 * New code should call services/storage.service.js directly.
 */
import { saveMediaBuffer, deleteStoredFile } from '../services/storage.service.js';
import { env } from '../config/env.js';
import { ApiError } from './ApiError.js';

const DATA_URL_PATTERN = /^data:([^;]+);base64,(.+)$/;

const parseDataUrl = (dataUrl) => {
  const match = String(dataUrl || '').match(DATA_URL_PATTERN);

  if (!match) {
    throw new ApiError(400, 'A valid base64 image data URL is required');
  }

  return { mimeType: match[1], base64: match[2] };
};

/**
 * Cloudinary folders arrive as `quickdrop/drivers/documents`; the upload root
 * takes the same shape, but only letters, numbers, `_`, `-` and `/`.
 *
 * Cloudinary allowed more, and taxi's folders were built on that: the default
 * CLOUDINARY_FOLDER is "Quick Drop-taxi", with a space, so every taxi upload was
 * refused ("Folder may only contain letters, numbers, /, _, and -") once these
 * helpers moved to local storage. Each segment is cleaned instead -- anything
 * else becomes `-` -- and `.`/`..` segments are dropped, so a caller's folder
 * can neither fail the upload nor climb out of the root. sanitizeUploadFolder
 * inside the storage service still has the final say.
 */
export const asStorageFolder = (folder) => {
  const cleaned = String(folder || env.cloudinary.folder || 'taxi')
    .replace(/\\/g, '/')
    .split('/')
    .map((segment) => segment.trim().replace(/[^A-Za-z0-9_-]+/g, '-').replace(/-{2,}/g, '-').replace(/^-+|-+$/g, ''))
    .filter((segment) => segment && segment !== '.' && segment !== '..')
    .join('/');
  return cleaned || 'taxi';
};

export const uploadBufferToCloudinary = async ({
  buffer,
  mimeType = 'image/jpeg',
  folder = env.cloudinary.folder,
  // Accepted for call-site compatibility. The stored name is generated by the
  // storage service, so these no longer shape the filename.
  publicIdPrefix = 'driver-document',
  publicIdSuffix = '',
  format = 'webp',
} = {}) => {
  if (!Buffer.isBuffer(buffer) || buffer.length === 0) {
    throw new ApiError(400, 'Image buffer is required');
  }

  const stored = await saveMediaBuffer(buffer, asStorageFolder(folder), { mimeType });

  return {
    secureUrl: stored.url,
    publicId: stored.path,
    resourceType: stored.resourceType,
    format: (stored.mimeType || '').split('/')[1] || '',
    bytes: stored.size,
    // Cloudinary reported these and some callers logged them. Nothing reads
    // them for a decision, and claiming dimensions we did not measure would be
    // worse than saying we do not know.
    width: null,
    height: null,
    originalFilename: stored.filename,
    createdAt: new Date().toISOString(),
    raw: stored,
  };
};

export const uploadDataUrlToCloudinary = async ({
  dataUrl,
  folder = env.cloudinary.folder,
  publicIdPrefix = 'driver-document',
  publicIdSuffix = '',
  format = 'webp',
} = {}) => {
  const { mimeType, base64 } = parseDataUrl(dataUrl);

  return uploadBufferToCloudinary({
    buffer: Buffer.from(base64, 'base64'),
    mimeType,
    folder,
    publicIdPrefix,
    publicIdSuffix,
    format,
  });
};

/** Remove a stored file by the `publicId` these helpers returned. */
export const deleteFromCloudinary = async (publicId) => deleteStoredFile(publicId);
